# Project information
site_name: jinqizh8
site_description: 'Personal Site'
site_author: 'jinqizh8'
site_url: 'https://jinqizh8.com'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/jinqizh8/jinqizh8'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Dmytro Danylyk'

# Documentation and theme
theme_dir: 'material'
site_favicon: 'images/favicon.ico'

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/jinqizh8'
    - type: 'twitter'
      link: 'https://twitter.com/jinqizh8'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jinqizh8'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc(permalink=true)

# Google Analytics
google_analytics:
  - 'UA-4482495-4'
  - 'auto'

pages:
    - About: index.md
    - Articles:
        - Android Data Sync - Part 1: articles/data-sync-part1.md
        - Android Data Sync - Part 2: articles/data-sync-part2.md
        - Concurrent database access: articles/concurrent-database.md
        - Lazy data loading from SQLite: articles/lazy-sqlite.md
    - Speaker: speaker-timeline.md
    - Contact: contact.md
    - Portfolio: portfolio.md
